### ISSUE TITLE
LocationArea Opacity

### ISSUE THREAD

**Issue by wonjiky** [teralytics/flowmap.gl#114]
Hello,

Is it possible to change the `locationArea` fill color when they are at `normal` state without the warning printing?
I am trying to match the `locationArea` color to match the default mapbox shape tile color and change the opacity when a `locationArea` is hovered.

For example, I have :
`locationAreas: {
            normal: "rgba(0,0,0,0)"
          }`

And it keeps on giving me this warning, `colors.js?4931:96 Invalid color:  rgba(NaN, NaN, NaN, 0.5)`
I have tried adding the color in as hex `#fff0` but no luck..

Thank you in advance!

**Comment by ilyabo** [comment]
Ah, I know what's the issue:

<img src=https://user-images.githubusercontent.com/351828/111687158-3e4a6900-882a-11eb-8ec9-154124edc19b.png width=300>

As a workaround, just use `rgba(255,255,255,0)`, since you set opacity to 0 anyways.
Or specify all colors for locationAreas: connected, highlighted, selected and outline.

**Comment by wonjiky** [comment]
Thank you so much for the quick response @ilyabo !
